CabBundle\Entity\Community:
    type: entity
    table: null
    repositoryClass: CabBundle\Repository\CommunityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    oneToMany:
        trips:
            targetEntity: CabBundle\Entity\Trip
            mappedBy: community

    manyToMany:
            peoples:
                targetEntity: CabBundle\Entity\People
                mappedBy: communities
                cascade: ['all']
