CabBundle\Entity\Community:
    type: entity
    table: null
    repositoryClass: CabBundle\Repository\CommunityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255


    manyToOne:
        people:
            targetEntity: CabBundle\Entity\People

    manyToMany:
            peoples:
                targetEntity: testBundle\Entity\People
                mappedBy: community
                cascade: ['all']
