trip_index:
    path:     /
    defaults: { _controller: "CabBundle:Trip:index" }
    methods:  GET

trip_show:
    path:     /{id}/show
    defaults: { _controller: "CabBundle:Trip:show" }
    methods:  GET

trip_new:
    path:     /new
    defaults: { _controller: "CabBundle:Trip:new" }
    methods:  [GET, POST]

trip_edit:
    path:     /{id}/edit
    defaults: { _controller: "CabBundle:Trip:edit" }
    methods:  [GET, POST]

trip_delete:
    path:     /{id}/delete
    defaults: { _controller: "CabBundle:Trip:delete" }
    methods:  DELETE
