<?php

namespace CabBundle\Repository;

/**
 * CommunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneBy($id){
        $qb = $this->createQueryBuilder('community');
        $qb->select('community')
            ->where('community.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();

    }
}