cab_community:
    resource: "@CabBundle/Resources/config/routing/community.yml"
    prefix:   /community

cab_people:
    resource: "@CabBundle/Resources/config/routing/people.yml"
    prefix:   /people

cab_trip:
    resource: "@CabBundle/Resources/config/routing/trip.yml"
    prefix:   /trip



cab_people:
    path:      /home/people
    defaults: { _controller: CabBundle:Home:people }

cab_community:
    path:      /home/community
    defaults: { _controller: CabBundle:Home:community }

cab_newcommunity:
    path:      /home/newcommunity
    defaults: { _controller: CabBundle:Home:newcommunity }

cab_mycommunity:
    path:      /home/mycommunity
    defaults: { _controller: CabBundle:Home:mycommunity }

cab_newtrip:
    path:      /home/newtrip
    defaults: { _controller: CabBundle:Home:newtrip }

cab_trip:
    path:      /home/trip
    defaults: { _controller: CabBundle:Home:trip }

cab_home:
    path:      /home/home
    defaults: { _controller: CabBundle:Home:home }

