cab_home:
    path:      /home/home
    defaults: { _controller: CabBundle:Home:home }

cab_people:
    path:      /home/people
    defaults: { _controller: CabBundle:Home:people }

cab_community:
    path:      /home/community
    defaults: { _controller: CabBundle:Home:community }

cab_newcommunity:
    path:      /home/newcommunity
    defaults: { _controller: CabBundle:Home:newcommunity }

cab_newtrip:
    path:      /home/newtrip
    defaults: { _controller: CabBundle:Home:newtrip }

cab_trip:
    path:      /home/trip
    defaults: { _controller: CabBundle:Home:trip }



