cab_community:
    resource: "@CabBundle/Resources/config/routing/community.yml"
    prefix:   /

cab_people:
    resource: "@CabBundle/Resources/config/routing/people.yml"
    prefix:   /people

cab_trip:
    resource: "@CabBundle/Resources/config/routing/trip.yml"
    prefix:   /trip


cab_home:
    path:      /
    defaults: { _controller: CabBundle:Community:home }

